### ISSUE TITLE
Image preview doesn't show in the proper terminal

### ISSUE THREAD

**Issue by eeeXun** [neeshy/lfimg#1]
![bug](https://user-images.githubusercontent.com/58657914/106478326-0be7e500-64e4-11eb-90d6-b916aa14651c.png)

As the picture,I previously open the right hand side terminal,and then open left hand side terminal later.
Then open "lf" on the right hand side,but the image showing on the left hand side terminal.

**Comment by yassinebridi** [comment]
I can't reproduce this, check out my config, it might help:
https://github.com/yassinebridi/.dotfiles/tree/master/lf/.config/lf

**Comment by eeeXun** [comment]
I finially find out that it's the terminal problem.
I use mate-terminal,which causes this problem.
Maybe I should switch to other terminal emulator.
And thank you @yassinebridi .
