### ISSUE TITLE
[help] supress verbose when open file by external program

### ISSUE THREAD

**Issue by roachsinai** [neeshy/lfimg#2]
Thanks for repo! It helps a lot.

My problem is when use the map `o` open a file like a `xml` file, there will be a text line in the bottom of lf windown: `Opening in existing browser session.`

Could you supress it directly or add a optional?

**Comment by neeshy** [comment]
I can't reproduce this. XML files open in an editor for me. The output that you saw suggests that a web browser is being used to open the file, so I tried opening an HTML file, and I still can't reproduce it.

**Comment by roachsinai** [comment]
Hi @neeshy are you using Firefox? Today I found verbose shows only when open file by chrome, no verbose if firefox was used.

**Comment by neeshy** [comment]
Yes, I was using firefox. I switched to chromium and still can't reproduce what you're seeing. Check your lfrc. It sounds like you've set the opener to be invoked with ! which directs lf to pipe the stdout of the opener to the bottom of the window.

**Comment by roachsinai** [comment]
Thanks for your suggestion, I'm so sorry for the late reply as not at home. 

My `lfrc` only have below settings:

```
set previewer ~/.config/lf/pv
set cleaner ~/.config/lf/cls

# define a custom 'open' command
cmd open $$OPENER $fx
cmd open-choose $OPENER_CHOOSE="true" $OPENER $fx
# dedicated keys for file opener actions
map o open
map O open-choose
# default is zh
map . set hidden!
```

I run `./lfimg` directly and can reproduce it.

**Comment by roachsinai** [comment]
And if I open chrome in terminal by `google-chrome-stable` also got that verbose.
